
UK_URL: "https://ofsistorage.blob.core.windows.net/publishlive/2022format/ConList.html"
RBI_URL: "https://www.un.org/securitycouncil/sanctions/1267/aq_sanctions_list"
US_URL: "https://www.treasury.gov/ofac/downloads/sdnlist.txt"
#DB_NAME: "kc_sanctions"
#DB_USER: "postgres"
#DB_PWD: "6y$WhW&c4Nx153DRKrVKI"
#DB_HOST: "database-2-instance-1.cax4yfaijbds.ap-southeast-1.rds.amazonaws.com"
#DB_PORT: "5432"
#
DB_NAME: "travancore_db"
DB_USER: "travancore"
DB_PWD: "x9zTW5!96q"
DB_HOST: "dev-kinara-analytics.c7bnqj62apqh.ap-south-1.rds.amazonaws.com"
DB_PORT: "3307"

